### ISSUE TITLE
Update all of the data!

### ISSUE THREAD

**Issue by zz-hh-aa** [theopensystemslab/fairhold-dashboard#110]
# Tasks
- [x] Write scripts for data update
- [x] Runs scripts to generate CSVs
- [ ] Write `updateData` script
- [ ] Push updates to remote repo

# Data

Pulling from previous documentation version for [`fh_calc`](https://github.com/theopensystemslab/fh_calc).

Looks like we'll be updating to 2022. 

# Data & sources
| Dataset | Source | Latest calendar year | Comments | Remote database? | Updated in remote database? | 
| -------- | ------- | ------- | ------- | ------- |------- |
| ITL lookup | [ONS Geoportal](https://geoportal.statistics.gov.uk/datasets/8c4d546ee4a446819b5ff39ff81cf009_0/explore) | 2024 updates to 2020, 2021, 2023 LAD codes | Unsure as to which LAD set we'll need | YES | | 
| Price paid | [HM Land Registry](https://www.gov.uk/government/statistical-data-sets/price-paid-data-downloads#yearly-file) | 2023 | | YES | |
| GDHI | [ONS](https://www.ons.gov.uk/economy/regionalaccounts/grossdisposablehouseholdincome/datasets/regionalgrossdisposablehouseholdincomegdhi) | 2022 (2024 release) | | YES | |
| Private rent | [ONS](https://www.ons.gov.uk/peoplepopulationandcommunity/housing/datasets/privaterentalmarketsummarystatisticsinengland) | 2022-23 | | YES | |
| Social rent inputs | [GOV UK](https://www.gov.uk/government/publications/direction-on-the-rent-standard-from-1-april-2020/policy-statement-on-rents-for-social-housing#appendix-a-information-for-calculating-formula-rents) | Info from 1 Apr 2020 onwards (inflation to 2023-24) | | YES | N/A | 
| House price index | [GOV UK](https://www.gov.uk/government/statistical-data-sets/uk-house-price-index-data-downloads-december-2023) | We only need 1999 for social rent calculations | | PARTIAL | N/A | 
| Gas bills | [DESNZ via GOV UK, 2.3.3](https://www.gov.uk/government/statistical-data-sets/annual-domestic-energy-price-statistics#history) | 2023-24 | They have prices per kwh already, will need to update our math | YES |  |
| Energy demand | [Studio PDP](https://studiopdp.com/think-blog/retrofit-six-key-principles) | N/A, accessed April 2024 | | NO | N/A |
